workflows:
  ios-release:
    name: BLEBikeNavi Release

    environment:
      xcode: latest

    scripts:
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "BLEBikeNavi.xcodeproj" \
            --scheme "BLEBikeNavi"

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
